version: '3.8'

services:
  ark_theisland:
    container_name: ark_theisland
    build: .
    volumes:
      - ./GameUserSettings.ini:/home/steam/ark/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini
      - ./theisland:/home/steam/ark/ShooterGame/Saved/TheIsland
      - ./clusters:/home/steam/ark/ShooterGame/Saved/clusters/YourClusterID
    ports:
      - 7777:7777/udp
      - 7778:7778/udp
      - 27015:27015/udp
    environment:
      - MAP=TheIsland
      - SESSION_NAME=Serveur_OCB_The_Island
      - SERVER_PASSWORD=
      - ADMIN_PASSWORD=YourAdminPassword
      - GAME_PORT=7777
      - QUERY_PORT=27015
      - RCON_PORT=32330
      - MAX_PLAYERS=70
      - CLUSTER_ID=YourClusterID
      - AltSaveDirectoryName=island

  ark_ragnarok:
    container_name: ark_ragnarok
    build: .
    volumes:
      - ./GameUserSettings.ini:/home/steam/ark/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini
      - ./ragnarok:/home/steam/ark/ShooterGame/Saved/Ragnarok
      - ./clusters:/home/steam/ark/ShooterGame/Saved/clusters/YourClusterID
    ports:
      - 7779:7779/udp
      - 7780:7780/udp
      - 27016:27016/udp
    environment:
      - MAP=Ragnarok
      - SESSION_NAME=Serveur_OCB_Ragnarock
      - SERVER_PASSWORD=
      - ADMIN_PASSWORD=YourRagnarokAdminPassword
      - GAME_PORT=7779
      - QUERY_PORT=27016
      - RCON_PORT=32331
      - MAX_PLAYERS=70
      - CLUSTER_ID=YourClusterID
      - AltSaveDirectoryName=Ragnarock
